#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

failures=0

echo "Running docs quality checks..."

check_paths=(
  "README.md"
  "CONTRIBUTING.md"
  "AGENTS.md"
  "CHANGELOG.md"
  "SECURITY.md"
  "backend/README.md"
  "backend/docs"
  "backend/migrations/README.md"
  "frontend/README.md"
  "docs/README.md"
  "docs/API.md"
  "docs/adr"
  "docs/assets"
  "docs/case-studies"
  "docs/data-sources"
  "docs/geocoding-research-plan.md"
  "docs/getting-started"
  "docs/architecture"
  "docs/development"
  "docs/index.md"
  "docs/maintenance-audit.md"
  "docs/ontario-methodology.md"
  "docs/ontario-research-findings.md"
  "docs/operations"
  "docs/reference"
  "docs/research"
  "docs/stakeholder-interviews"
  "docs/stakeholder-feedback.md"
  "docs/openapi.yaml"
  "docs/screenshot-guide.md"
  "docs/planning/README.md"
  "docs/planning/index.md"
  "docs/planning/manual-tasks.md"
  "docs/planning/public-health-data-hub-freshness-safety-rules.md"
  "docs/planning/public-health-data-hub-metadata-contract.md"
  "docs/planning/public-health-data-hub-municipal-inspection-pilot-decision.md"
  "docs/planning/roadmap-process.md"
  "docs/planning/roadmap.md"
  ".github/workflows/README.md"
)

mapfile -t maintenance_logs < <(
  find "docs/planning/archive" -maxdepth 1 -type f -name "maintenance-*.md" 2>/dev/null | sort
)
check_paths+=("${maintenance_logs[@]}")

mapfile -t all_md_files < <(
  find "${check_paths[@]}" -type f -name "*.md" 2>/dev/null | sort
)

exclude_files=(
  "docs/adr/template.md"
  "docs/planning/expansion-roadmap.md"
  "docs/planning/competitor-design-analysis.md"
  "docs/planning/ux-seo-implementation-plan.md"
)

md_files=()
for file in "${all_md_files[@]}"; do
  skip_file=0
  for excluded in "${exclude_files[@]}"; do
    if [[ "${file}" == "${excluded}" ]]; then
      skip_file=1
      break
    fi
  done

  if [[ "${skip_file}" -eq 0 ]]; then
    md_files+=("${file}")
  fi
done

if [[ ${#md_files[@]} -eq 0 ]]; then
  echo "No markdown files found for checks."
  exit 1
fi

mapfile -t non_markdown_public_files < <(
  find "${check_paths[@]}" -type f \( -name "*.html" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" -o -name "*.csv" \) 2>/dev/null | sort
)

mapfile -t public_text_files < <(
  {
    printf '%s\n' "${md_files[@]}"
    printf '%s\n' "${non_markdown_public_files[@]}"
  } | awk 'NF && !seen[$0]++'
)

file_url_link_pattern="\\]\\(file://|href=[\"']file://|:[[:space:]]*[\"']?file://|(^|,)[[:space:]]*\"?file://"
non_human_attribution_pattern="^[[:space:]]*(Author|Authors|Contributor|Contributors|Co-authored-by|Generated by|Created by|Written by):[[:space:]]*.*(claude|codex|gemini|chatgpt|ai assistant|automated tool)|generated by[[:space:]]+(claude|codex|gemini|chatgpt|ai assistant|automated tool)|created by[[:space:]]+(claude|codex|gemini|chatgpt|ai assistant|automated tool)|written by[[:space:]]+(claude|codex|gemini|chatgpt|ai assistant|automated tool)"
non_human_commit_identity_pattern="claude|codex|gemini|chatgpt|copilot|openai|ai assistant|automated tool"
non_human_commit_trailer_pattern="^[[:space:]]*(Author|Authors|Contributor|Contributors|Co-authored-by|Generated by|Generated-by|Created by|Created-by|Written by|Written-by):[[:space:]]*.*(${non_human_commit_identity_pattern})"
public_boundary_pattern="OMSAS|CanMEDS|medical school|physician-innovator|application committee|personal statement|Scholar narrative|Leader Role|Professional Role|Scholar Role|Automated Agent|Owner:.*(agent|tool)|Author:.*(agent|tool)|/home/jer|(^|[[:space:]])/(home|Users)/[[:alnum:]_.-]+|/mnt/|wsl\\.localhost|wsl\\$|\\\\\\\\wsl|[a-z]:\\\\users|[a-z]:/users|\\\\\\\\users\\\\\\\\|tailscale|direct-vps|direct VPS|shared VPS|platform-ops|/etc/projects-merge|Neon|Netlify|Caddy|systemd|Pushover|PUSHOVER|private ip"
active_cadence_drift_pattern="currently runs hourly via GitHub Actions|current hourly GitHub Actions|hourly GitHub Actions scraper cadence"

echo
echo "[1/11] Checking for absolute file:// links..."
if grep -nE "${file_url_link_pattern}" "${public_text_files[@]}"; then
  failures=1
else
  echo "OK: no file:// links found."
fi

echo
echo "[2/11] Checking for non-human authorship attribution markers..."
mapfile -t tracked_attribution_files < <(
  git ls-files | while IFS= read -r file; do
    case "${file}" in
      .env|.env.local|*/.env|*/.env.local|key.txt|*/key.txt|*.pem|*.key|private/*|*/private/*)
        continue
        ;;
    esac

    case "${file}" in
      *.md|*.txt|*.rst|*.py|*.ts|*.tsx|*.js|*.jsx|*.json|*.yml|*.yaml|*.sh|*.sql|*.css|*.html|*.csv|*.toml|*.ini|*.cfg)
        if [[ -e "${file}" ]]; then
          printf '%s\n' "${file}"
        fi
        ;;
    esac
  done
)
mapfile -t attribution_files < <(
  {
    printf '%s\n' "${tracked_attribution_files[@]}"
    printf '%s\n' "${public_text_files[@]}"
  } | awk 'NF && !seen[$0]++'
)
if grep -nEi "${non_human_attribution_pattern}" "${attribution_files[@]}"; then
  failures=1
else
  echo "OK: no non-human authorship attribution markers found."
fi

echo
echo "[3/11] Checking Git history authorship metadata..."
if git rev-parse --git-dir >/dev/null 2>&1 && git rev-parse --verify HEAD >/dev/null 2>&1; then
  if git log --all --format='%H %an <%ae> %cn <%ce>' | grep -Ei "${non_human_commit_identity_pattern}"; then
    echo "Git history contains non-human author/committer metadata."
    failures=1
  else
    echo "OK: no non-human author/committer identities found in available Git history."
  fi

  if git log --all --format='%H%n%B' | grep -Ei "${non_human_commit_trailer_pattern}"; then
    echo "Git history contains non-human authorship or attribution trailers."
    failures=1
  else
    echo "OK: no non-human authorship trailers found in available Git history."
  fi
else
  echo "OK: no commit history available for Git metadata audit."
fi

echo
echo
echo "[4/11] Checking agent-entrypoint symlinks..."
for agent_entrypoint in "CLAUDE.md" "GEMINI.md"; do
  if [[ ! -L "${agent_entrypoint}" ]]; then
    echo "${agent_entrypoint} must remain a relative symlink to AGENTS.md"
    failures=1
    continue
  fi

  if [[ "$(readlink "${agent_entrypoint}")" != "AGENTS.md" ]]; then
    echo "${agent_entrypoint} must point to AGENTS.md"
    failures=1
  else
    echo "OK: ${agent_entrypoint} points to AGENTS.md"
  fi
done

echo
echo "[5/11] Checking AGENTS ontology constants..."
if python3 - <<'PY'
import ast
import re
import sys
from pathlib import Path

enum_path = Path("backend/src/waittime/core/enums.py")
agents_path = Path("AGENTS.md")

tree = ast.parse(enum_path.read_text(encoding="utf-8"))
agents_text = agents_path.read_text(encoding="utf-8")

constant_to_class = {
    "METRIC_FAMILY": "MetricFamily",
    "START_EVENT": "StartEvent",
    "END_EVENT": "EndEvent",
    "STATISTIC_TYPE": "StatisticType",
    "PATIENT_SCOPE": "PatientScope",
}


def enum_values(class_name: str) -> list[str]:
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            values = []
            for statement in node.body:
                if not isinstance(statement, ast.Assign):
                    continue
                if not isinstance(statement.value, ast.Constant):
                    continue
                if isinstance(statement.value.value, str):
                    values.append(statement.value.value)
            return values
    raise ValueError(f"Missing enum class {class_name}")


def agents_values(constant_name: str) -> list[str]:
    match = re.search(
        rf"^{constant_name}\s*=\s*(\[[^\]]*\])",
        agents_text,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise ValueError(f"Missing AGENTS.md constant {constant_name}")
    value = ast.literal_eval(match.group(1))
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"AGENTS.md constant {constant_name} must be a string list")
    return value


mismatches = []
for constant_name, class_name in constant_to_class.items():
    expected = enum_values(class_name)
    actual = agents_values(constant_name)
    if actual != expected:
        mismatches.append(
            f"{constant_name}: AGENTS.md has {actual}, {enum_path} has {expected}"
        )

if mismatches:
    print("AGENTS.md ontology constants are out of sync:")
    for mismatch in mismatches:
        print(f"- {mismatch}")
    sys.exit(1)

print("OK: AGENTS.md ontology constants match implemented enums")
PY
then
  :
else
  failures=1
fi

echo
echo "[6/11] Checking Docs CI path-filter coverage..."
docs_ci_file=".github/workflows/docs-ci.yml"
required_docs_ci_patterns=(
  '"**/*.md"'
  '"**/*.txt"'
  '"**/*.rst"'
  '"**/*.py"'
  '"**/*.ts"'
  '"**/*.tsx"'
  '"**/*.js"'
  '"**/*.jsx"'
  '"**/*.json"'
  '"**/*.yml"'
  '"**/*.yaml"'
  '"**/*.sh"'
  '"**/*.sql"'
  '"**/*.css"'
  '"**/*.html"'
  '"**/*.csv"'
  '"**/*.toml"'
  '"**/*.ini"'
  '"**/*.cfg"'
  '"docs/**"'
)

docs_ci_event_block() {
  local event_name="$1"
  awk -v event_name="${event_name}" '
    $0 == "  " event_name ":" {
      in_event = 1
      next
    }
    in_event && $0 ~ /^  [A-Za-z0-9_-]+:/ {
      exit
    }
    in_event {
      print
    }
  ' "${docs_ci_file}"
}

for docs_ci_event in "pull_request" "push"; do
  docs_ci_block="$(docs_ci_event_block "${docs_ci_event}")"
  if [[ -z "${docs_ci_block}" ]]; then
    echo "Docs CI is missing ${docs_ci_event} trigger block"
    failures=1
    continue
  fi

  for required_pattern in "${required_docs_ci_patterns[@]}"; do
    if grep -Fq -- "- ${required_pattern}" <<<"${docs_ci_block}"; then
      echo "OK: Docs CI ${docs_ci_event} includes ${required_pattern}"
    else
      echo "Docs CI ${docs_ci_event} path filters must include ${required_pattern}"
      failures=1
    fi
  done
done

if grep -Fq "workflow_dispatch:" "${docs_ci_file}"; then
  echo "OK: Docs CI has manual dispatch"
else
  echo "Docs CI must keep workflow_dispatch for manual verification"
  failures=1
fi

if grep -Eq "fetch-depth:[[:space:]]*0" "${docs_ci_file}"; then
  echo "OK: Docs CI fetches full history for authorship audit"
else
  echo "Docs CI checkout must use fetch-depth: 0 for commit authorship audit"
  failures=1
fi

echo
echo "[7/11] Checking public documentation boundary terms..."
if grep -nEi "${public_boundary_pattern}" "${public_text_files[@]}"; then
  failures=1
else
  echo "OK: no public-boundary marker terms found."
fi

echo
echo "[8/11] Checking active-doc operational cadence wording..."
active_cadence_files=()
for file in "${public_text_files[@]}"; do
  case "${file}" in
    docs/planning/archive/*)
      continue
      ;;
  esac
  active_cadence_files+=("${file}")
done

if grep -nEi "${active_cadence_drift_pattern}" "${active_cadence_files[@]}"; then
  echo "Active docs must not claim current hourly GitHub Actions ingestion while manual-dispatch posture is active."
  failures=1
else
  echo "OK: active docs avoid stale hourly GitHub Actions cadence claims."
fi

echo
echo "[9/11] Checking repository-relative markdown links..."
check_markdown_link_target() {
  local file="$1"
  local file_dir="$2"
  local raw_link="$3"
  local link
  local target

  if [[ "${raw_link}" == "<"*">"* ]]; then
    link="${raw_link#<}"
    link="${link%%>*}"
  else
    link="${raw_link%%[[:space:]]*}"
  fi

  link="${link%%#*}"
  link="${link%%\\?*}"

  if [[ -z "${link}" ]]; then
    return
  fi

  if [[ "${link}" =~ ^(https?://|mailto:|#) ]]; then
    return
  fi

  if [[ "${link}" =~ ^[a-zA-Z]+: ]]; then
    return
  fi

  if [[ "${link}" == /* ]]; then
    target="${ROOT_DIR}${link}"
  else
    target="${ROOT_DIR}/${file_dir}/${link}"
  fi

  if [[ ! -e "${target}" ]]; then
    echo "Broken link target in ${file}: ${raw_link}"
    failures=1
  fi
}

while IFS= read -r file; do
  file_dir="$(dirname "${file}")"

  while IFS= read -r raw_link; do
    check_markdown_link_target "${file}" "${file_dir}" "${raw_link}"
  done < <(
    perl -nE 'while(/\[[^\]]+\]\(([^)]+)\)/g){ say $1 }' "${file}"
    perl -nE 'if(/^\s*\[[^\]]+\]:\s*(<[^>]+>|\S+)/){ say $1 }' "${file}"
  )
done < <(printf "%s\n" "${md_files[@]}")

echo
echo "[10/11] Checking clinical-safety and comparability guardrails..."
require_pattern() {
  local file="$1"
  local pattern="$2"
  local description="$3"

  if grep -Eq "${pattern}" "${file}"; then
    echo "OK: ${description}"
  else
    echo "Missing required guardrail in ${file}: ${description}"
    failures=1
  fi
}

require_pattern "README.md" "does not provide medical advice" "README states non-medical-advice boundary"
require_pattern "README.md" "Call 911 for emergencies" "README keeps emergency disclaimer"
require_pattern "README.md" "directly comparable" "README preserves comparability framing"
require_pattern "docs/API.md" "not a triage or medical advice service" "API docs state non-triage boundary"
require_pattern "docs/API.md" "ontology dimensions match" "API docs preserve ontology comparison rule"
require_pattern "docs/planning/roadmap.md" "hospital-choice recommendations" "Roadmap preserves hospital-choice boundary"
require_pattern "docs/planning/roadmap.md" "metric family, start event, end event, and statistic type" "Roadmap preserves four-field comparability rule"
require_pattern "docs/research/export-methodology-interpretation-guide.md" "medical advice, triage guidance, or care-site" "Export guide blocks clinical/recommendation misuse"
require_pattern "docs/research/export-methodology-interpretation-guide.md" "metric_family" "Export guide documents metric_family"
require_pattern "docs/research/export-methodology-interpretation-guide.md" "start_event" "Export guide documents start_event"
require_pattern "docs/research/export-methodology-interpretation-guide.md" "end_event" "Export guide documents end_event"
require_pattern "docs/research/export-methodology-interpretation-guide.md" "statistic_type" "Export guide documents statistic_type"
require_pattern "docs/case-studies/ottawa-gatineau-divergence.md" "not directly comparable" "Case study preserves divergence conclusion"

echo
echo "[11/11] Checking roadmap consistency..."
if python3 backend/scripts/verify_roadmap_consistency.py; then
  echo "OK: roadmap consistency checks passed."
else
  echo "Roadmap consistency check failed."
  failures=1
fi

if [[ "${failures}" -ne 0 ]]; then
  echo
  echo "Docs quality checks failed."
  exit 1
fi

echo
echo "Docs quality checks passed."
