name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/deploy-docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Configure Git Credentials
        run: |
          git config user.name "Jeremy Dawson"
          git config user.email "jeremyjdawson@gmail.com"

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install "mkdocs<2" mkdocs-material mkdocs-minify-plugin

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
